spring.application.name=asr-api

spring.message.encoding=UTF-8
server.port=8200

server.adminPort=8000
server.adminPathPrefix=/admin/

server.need_signature=false

#1M=1048576
asr.max_audio_file_size=1048576
asr.server_url=http://127.0.0.1:12435/inference
asr.reuse_history=true

asr.use_llm_correct=true
llm.server_url=https://api.deepseek.com/chat/completions
llm.model_name=deepseek-v4-flash
# 大模型服务密钥，如果大模型服务需要认证请填写，例如 OpenAI/通义千问等在线服务；Ollama 本地服务通常无需填写
llm.api_key=sk-XXXX

# mysql????
# mysql??????????mysql?????? create database asr; asr????????IM?????????"wfchat"?????????
##*********************** mysql DB begin *************************
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/asr?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect.storage_engine=innodb
#spring.sql.init.mode=always
##*********************** mysql DB end ***************************
